# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vicboma1

on:
  push:
    branches: master
  pull_request:
    branches: 
    - develop

jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: CI
      run: npm ci
    - name: Test
      run: npm test
